### ISSUE TITLE
[BUG] "Release project" action failing

### ISSUE THREAD

**Issue by juancho0202** [com-pas/compas-scl-data-service#354]
**Subject of the issue**

The github action "Release project" failed for the release v0.14.0 at the "Deploy with maven to Github packages and Docker hub" step. The following error was logged:

```console
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:08 min
[INFO] Finished at: 2023-10-05T13:03:34Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.4.Final:build (build-basex) on project app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildNativeImageJar threw an exception: java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /home/runner/work/compas-scl-data-service/compas-scl-data-service/app/target/basex-quarkus-app/app-0.14.0-native-image-source-jar/lib/com.fasterxml.jackson.core.jackson-databind-2.14.2.jar
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
Error:  	at java.base/java.lang.Thread.run(Thread.java:833)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  Caused by: java.nio.file.NoSuchFileException: /home/runner/work/compas-scl-data-service/compas-scl-data-service/app/target/basex-quarkus-app/app-0.14.0-native-image-source-jar/lib/com.fasterxml.jackson.core.jackson-databind-2.14.2.jar
Error:  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
Error:  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Error:  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Error:  	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246)
Error:  	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
Error:  	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
Error:  	at java.base/java.nio.file.Files.copy(Files.java:1305)
Error:  	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyLibraryJars(JarResultBuildStep.java:1101)
Error:  	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.doLegacyThinJarGeneration(JarResultBuildStep.java:1069)
Error:  	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageThinJar(JarResultBuildStep.java:1011)
Error:  	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageJar(JarResultBuildStep.java:975)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
Error:  	... 6 more
Error:  	Suppressed: java.nio.file.NoSuchFileException: /home/runner/work/compas-scl-data-service/compas-scl-data-service/app/target/basex-quarkus-app/app-0.14.0-native-image-source-jar/app-0.14.0-runner.jar
Error:  		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
Error:  		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Error:  		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Error:  		at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:825)
Error:  		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.lambda$removeFileSystem$0(ZipFileSystemProvider.java:305)
Error:  		at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
Error:  		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:307)
Error:  		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:526)
Error:  		at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageThinJar(JarResultBuildStep.java:999)
Error:  		... 12 more
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :app
Error: Process completed with exit code 1.
```

**Expected behavior**
All the steps in the "Release project" action run successfully.

**Actual behavior**
As described in the subject.

**Comment by Sander3003** [comment]
Solution: add a time-out step;

**Comment by Sander3003** [comment]
Make a pull-request to merge develop to main.

**Comment by Sander3003** [comment]
Main is merged with development.

**Comment by juancho0202** [comment]
@Sander3003 the acceptance criteria of this issue has not been met yet. Needs a release and check the GitHub action before you can close this.

**Comment by pascalwilbrink** [comment]
There are no Acceptance criteria on this issue.

**Comment by juancho0202** [comment]
It was proposed by @pascalwilbrink that specifying a target branch in the release-please workflow could fix this issue
